name: Dependency Demo

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Building Application"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Running Tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: echo "Deploying Application"
